# Use an official python runtime as a parent image
FROM python:3.11-slim

# set the working directory in the container
WORKDIR /app

# copy DummyApp.py to the container
COPY DummyApp.py .

# run the command to execute the app
CMD ["python", "DummyApp.py"]





